shared_mem.c: fix compliation
Compilation was failing on my machine with
```
mpicc -DFUNDERSC=1 -mcmodel=large -O3 -mtune=native -DDOUBLE_PRECISION
-std=c99 -o shared_mem.o -c shared_mem.c
shared_mem.c: In function ‘create_shm’:
shared_mem.c:62:9: error: implicit declaration of function ‘ftruncate’
[-Wimplicit-function-declaration]
   62 |     if (ftruncate(shm_fd, size) == -1) {
      |         ^~~~~~~~~
```
I still get a bizarre crash during runtime compilation, though.

This issue was exposed by Touko's recent commit a03fd9d1f5dd that
automatically enabled farray_alloc while using GPUs.

Not sure why the auto-tests are not catching this. Too-old glibc
versions (<2.12), perhaps?

My software versions:
* glibc 2.43
* gcc 15.2.1