Added farg.f which is sometimes needed to avoid the error message   undefined reference to `f__xargc' with some combinations of mpich and compiler (in this case: mpich compiled with g77 as is standard practice, in combination with ifort 8.1).
I am reluctant to make the resulting farg.o [sic!] a dependency of *.x, as
this applies only to very few machines. Currently this dependencey is just
hacked together in ~/.adapt-mkfile.incl on the machine in question.

Wolfgang [in the disguise of Axel]