added options for Nordita cluster which now has the name ns0 (instead of nq0).  But it doesn't work; here is what I get: --------------------------------------------------------------------------   mpif77  -O3 -u -c start.f90      program START
  167 Lines Compiled
  mpif77  -O3 -u start.o cparam.o cdata.o general.o slices.o deriv.o boundcond.o initcond.o register.o prints.o notimeavg.o sub.o
  io_dist.o param_io.o mpicomm.o noglobal.o visc_const.o hydro.o density.o forcing.o nograv.o nointerstellar.o noentropy.o nomagnetic.o
  noshear.o nopscalar.o noradiation.o nofft.o fftpack.o  debug_c.o -static -L/opt/lam/lib -lmpi -llamf77mpi -llam   -o start.x
  mpicomm.o: In function `mpicomm..mpicomm_init_':
  mpicomm.o(.text+0x11): undefined reference to `mpi_init_'
--------------------------------------------------------------------------

In my sys/.cshrc.nq0 file (which is being used) I also set:
--------------------------------------------------------------------------
  if (-d /opt/intel/compiler60) then
    setenv LAMHF77 ifc
    setenv LM_LICENSE_FILE /home/brandenb/etc/license/l_for_77355822.lic
    setenv LD_LIBRARY_PATH /opt/intel/compiler60/ia32/lib:$LD_LIBRARY_PATH
    setenv PATH $HOME/bin:/opt/intel/compiler60/ia32/bin:/usr/opt/lam/bin:$PATH
  endif
--------------------------------------------------------------------------
Any suggestions? Is it a problem of lammpi not being correctly installed?