Revert "MR: changed object order in link commands to calm the CRAY compiler"
This reverts commit 50d9750838f86aacc9ce0f8db49331ea35bc1a11.

It broke my samples

/opt/local/libexec/openmpi-gcc11/mpif90 -O -O0 -Wall -finit-real=NaN -finit-integer=-2147483648 -g -fbacktrace -fimplicit-none -fcheck=all -ffpe-trap=invalid,zero,overflow,denormal -O1 -I/opt/local/include -O0 -fdefault-real-8 -fdefault-double-8     -o border_profiles.o -c border_profiles.f90
border_profiles.f90:57:11:

   57 |       use SharedVariables, only: get_shared_variable
      |           1
Fatal Error: Cannot open module file 'sharedvariables.mod' for reading at (1): No such file or directory