sourceme: try to fix with older versions of git
Touko says he gets
```
  if [ "$(git -C $PENCIL_HOME config get pull.rebase)" = "false" ]; then
```
outputs
```
error: key does not contain a section: get
```
My suspicion is that the 'get' option was only added in recent versions
of git.

The manpage on my system indeed says that invoking `git config` without
a subcommand is deprecated. Hopefully it won't break soon.