particles_stalker.f90: fix reloading
samples/helical-MHDturb was failing while reloading with
```
Acquiring f-array scratch area: scratch
FATAL ERROR: acquire_scratch_area: f-array scratch area name already
exists!!!!
```
Still fails because there are more allocations done later on.