grid.f90: avoid out-of-bounds access in calc_bound_coeffs
My change in grid.f90 (in this commit) leads to a compilation error:
```
grid.f90:3073:28:

 3073 |       call calc_coeffs_1(dc,coeffs(:,BOT))
      |                            1
Error: Actual argument contains too few elements for dummy argument
‘coeffs’ (2/3) at (1)
```
so I have also changed the size of the `coeffs` array arg of
`noderiv.f90:calc_coeffs_1`.
```
-      real, dimension(-1:1), intent(out) :: coeffs
+      real, dimension(-0:0), intent(out) :: coeffs
```
Seems reasonable, since nghost=0 with noderiv.f90

I think Touko was trying to fix the above compilation error in his
commit cec998d48930 , but that leads to out-of-bounds access for me:
```
Fortran runtime error: Index '0' of dimension 2 of array 'coeffs'
outside of expected range (1:2)
```

Surprisingly, the autotests on pencil-code.org did not fail. Are they
not using bounds checking?