noderiv: calc_coeffs_1: fix dimensions of grid
Should fix compilation of the axionSU2back sample on my machine:
```
grid.f90:3067:25:

 3067 |       call calc_coeffs_1(dc,coeffs(:,BOT))
      |                         1
Error: Actual argument contains too few elements for dummy argument
‘grid’ (0/2) at (1)
```

Relevant previous commit: ef17c109206c94d951134f67836e2292bb3c0a04

I'm pretty sure the sample was working in that commit, but something
seems to have changed in the interim.